apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: mycontainerregistryteldahtest.azurecr.io/helloworld:15
        name: new-hello-world
        ports:
        - containerPort: 8080
          name: demo-http
