apiVersion: v1
kind: Service
metadata:
  name: hello-world-metrics
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9101
    targetPort: metrics
  selector:
    app: hello-world
